# Generated by Django 2.0.10 on 2019-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertas',
            name='id',
        ),
        migrations.AlterField(
            model_name='alertas',
            name='idAlert',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
