# Generated by Django 2.0.10 on 2019-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddd', '0002_auto_20190430_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='descrip',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='titulo',
            field=models.TextField(max_length=25),
        ),
    ]
