# Generated by Django 2.0.10 on 2019-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddd', '0003_auto_20190503_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='descrip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='titulo',
            field=models.CharField(max_length=25),
        ),
    ]
