# Generated by Django 2.0.10 on 2020-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddd', '0004_auto_20190503_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('cemptitu', models.IntegerField()),
                ('ddd_grp1', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
    ]
