# Generated by Django 2.0.10 on 2020-09-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddd', '0005_informe001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe001',
            old_name='ddd_grp1',
            new_name='segmento',
        ),
    ]
